[package]
name = "roti"
version = "0.1.0"
authors = ["Christopher Altona <caltona1@gmail.com>"]
edition = "2018"

[dependencies]

actix-web = "3.3.2"
serde = "1.0.119"
serde_json = "1.0.61"
log = "0.4.13"
env_logger = "0.8.2"